---
version: "3.6"

services:
  search_service_test:
    build:
      context: .
      dockerfile: test.DockerFile
    depends_on: [localstack]
    working_dir: /go/src/app
    env_file:
      - docker-compose.env
    volumes:
      - .:/go/src/app
  search_service_gosec:
    image: securego/gosec:v2.7.0
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    entrypoint: ["/bin/gosec", "/go/src/app/..."]
