---
services:
  search-service:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/search-service:latest
    build:
      dockerfile: docker/search-service/Dockerfile
      context: .
    ports: ["8000:8000"]
    depends_on:
      localstack:
        condition: service_healthy
    env_file:
      - docker-compose.env

  localstack:
    image: localstack/localstack:4.14.0@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    environment:
      AWS_DEFAULT_REGION: eu-west-1
      SERVICES: es, secretsmanager
    networks:
      default:
        aliases:
          - search-service.eu-west-1.opensearch.localhost.localstack.cloud
    volumes:
      - "./scripts/localstack/init:/etc/localstack/init/ready.d"
      - "./scripts/localstack/wait:/scripts/wait"
    healthcheck:
      test: bash /scripts/wait/healthcheck.sh
      interval: 30s
      timeout: 5s
      retries: 8

  go-lint:
    image: golangci/golangci-lint:v2.12.2@sha256:5cceeef04e53efe1470638d4b4b4f5ceefd574955ab3941b2d9a68a8c9ad5240
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
      - ./.cache/golangci-lint/v1.53.3:/root/.cache
    command: golangci-lint run -v --timeout 5m --enable gosec --output.text.path stdout --output.sarif.path test-results/golangci-lint.sarif

  postgres:
    image: postgres:13.23@sha256:4689940c683801b4ab839ab3b0a0a3555a5fe425371422310944e89eca7d8068
    ports: ["5434:5432"]
    command: postgres
    environment:
      POSTGRES_USER: searchservice
      POSTGRES_PASSWORD: searchservice
      POSTGRES_DB: searchservice
      PGPASSWORD: searchservice

  test-runner:
    build:
      context: docker/test-runner/
    command: gotestsum --junitfile test-results/unit-tests.xml -- ./... -coverprofile=test-results/test-coverage.txt
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
      - ./.gocache:/go/pkg/mod
    env_file:
      - docker-compose.env

  swagger-ui:
    image: swaggerapi/swagger-ui@sha256:135a9ced4005a947bbb1757bc509309d88519d985aa0f5616f4fdfab1eba6ff6
    environment:
      SWAGGER_JSON: /tmp/openapi.yml
    volumes:
      - ./docs/openapi/openapi.yml:/tmp/openapi.yml
    ports:
      - 8383:8080

  swagger-generate:
    image: quay.io/goswagger/swagger@sha256:e4e89fcb84027a313d8d315a32cecaf2da76e2d8efb9546124082021b6e74389
    environment:
      GO111MODULE: "off"
      GOPATH: /go
    volumes:
      - ./:/go/src
    working_dir: /go/src
    entrypoint: ["swagger", "generate", "spec", "-o", "/go/src/docs/openapi/openapi.yml", "--scan-models"]

  pact-verifier:
    image: pactfoundation/pact-ref-verifier@sha256:514b680cd0ad2fa95c6df7a541e3b03c8dd1176de26e84e58a349de96e305bce
    depends_on:
      - pact-provider-state-api
    entrypoint:
      - pact_verifier_cli
      - --hostname=search-service
      - --port=8000
      - --base-path=/services/search-service/
      - --broker-url=https://pact-broker.api.opg.service.justice.gov.uk/
      - --provider-name=search-service
      - --header=${PACT_HEADER:-}
      - --loglevel=debug
      - --state-change-url=http://pact-provider-state-api:5175/provider_state_change
      - --state-change-teardown

  pact-provider-state-api:
    depends_on:
      - search-service
    build:
      context: pact
      dockerfile: Dockerfile
    ports:
      - 8175:5175
    volumes:
      - ./pact/api:/usr/src/app/api
    environment:
      SEARCH_SERVICE_URL: http://search-service:8000/services/search-service/
