---
version: "3.6"

services:
  search_service_test:
    build:
      context: .
      dockerfile: test.DockerFile
    depends_on: [localstack]
    working_dir: /go/src/app
    env_file:
      - docker-compose.env
    volumes:
      - .:/go/src/app
